"""Typed contracts for the CoursePilot runtime foundation."""

from coursepilot.domain.artifact import ArtifactRef, ArtifactVersion, StorageKind
from coursepilot.domain.context import ContextPackageRef
from coursepilot.domain.exam import (
    ExamArtifact,
    ExamBlueprintV2,
    ExamGlobalReport,
    ExamQuestion,
    OptionAssessment,
    QuestionBatchPlan,
    QuestionBatchResult,
    QuestionSlotPlan,
    batch_job_id,
    question_id,
)
from coursepilot.domain.interrupts import (
    ApprovalScope,
    ChangeMode,
    DecisionAction,
    HumanDecision,
    InterruptPayload,
    InterruptStatus,
    InterruptType,
)
from coursepilot.domain.lesson import (
    AllocationImportance,
    KnowledgePointAllocation,
    LessonActivity,
    LessonArtifact,
    LessonBlueprint,
    LessonEvidenceBinding,
    LessonFact,
    LessonSessionArtifact,
    LessonSessionBlueprint,
)
from coursepilot.domain.ppt import (
    PPTArtifact,
    PPTRenderReport,
    SlideArchitecture,
    SlideAssetPlaceholder,
    SlideCitation,
    SlideContent,
    SlidePlan,
)
from coursepilot.domain.runtime import CommonGraphState, NodeResult, NodeStatus, RunContext
from coursepilot.domain.task import BusinessTask, TaskStatus, WorkflowType

__all__ = [
    "ArtifactRef",
    "ArtifactVersion",
    "BusinessTask",
    "CommonGraphState",
    "ContextPackageRef",
    "NodeResult",
    "NodeStatus",
    "RunContext",
    "StorageKind",
    "TaskStatus",
    "WorkflowType",
    "AllocationImportance",
    "KnowledgePointAllocation",
    "LessonActivity",
    "LessonArtifact",
    "LessonBlueprint",
    "LessonEvidenceBinding",
    "LessonFact",
    "LessonSessionArtifact",
    "LessonSessionBlueprint",
    "ApprovalScope",
    "ChangeMode",
    "DecisionAction",
    "HumanDecision",
    "InterruptPayload",
    "InterruptStatus",
    "InterruptType",
    "ExamArtifact",
    "ExamBlueprintV2",
    "ExamGlobalReport",
    "ExamQuestion",
    "OptionAssessment",
    "QuestionBatchPlan",
    "QuestionBatchResult",
    "QuestionSlotPlan",
    "batch_job_id",
    "question_id",
    "PPTArtifact",
    "PPTRenderReport",
    "SlideArchitecture",
    "SlideCitation",
    "SlideContent",
    "SlidePlan",
    "SlideAssetPlaceholder",
]
