FROM python:3.12.3-slim

WORKDIR /app

ARG PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
ARG PIP_DEFAULT_TIMEOUT=120
ARG UV_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple

ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV UV_COMPILE_BYTECODE=1
ENV PIP_INDEX_URL=${PIP_INDEX_URL}
ENV PIP_DEFAULT_TIMEOUT=${PIP_DEFAULT_TIMEOUT}
ENV UV_INDEX_URL=${UV_INDEX_URL}

COPY pyproject.toml .
COPY uv.lock .
RUN pip install --no-cache-dir uv
RUN uv sync --frozen --no-install-project --no-dev

COPY src/agents/ ./agents/
COPY src/core/ ./core/
COPY src/memory/ ./memory/
COPY src/schema/ ./schema/
COPY src/service/ ./service/
COPY src/run_service.py .
# 新增
COPY src/coursepilot/ ./coursepilot/
COPY deepseek_v3_tokenizer/ ./deepseek_v3_tokenizer/
COPY alembic.ini .
COPY alembic/ ./alembic/

CMD ["python", "run_service.py"]
